version: "3"
services:
  geth:
    image: ethereum/client-go
    container_name: ethereum_geth
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - /${HOME}/.ethereum_geth:/root
      - /${HOME}/.ethereum_private:/ethereum_private
    command: --datadir=/ethereum_private --networkid 9871 --rpc --rpcaddr "0.0.0.0" console
#    TODO